### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [agrafix/highjson#3]
```
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:127:37: error:
highjson                       >     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
highjson                       >     • In the first argument of ‘(.=)’, namely ‘so_jsonKey f’
highjson                       >       In the expression: so_jsonKey f .= body
highjson                       >       In an equation for ‘encoder’: encoder = so_jsonKey f .= body
highjson                       >     |
highjson                       > 127 |                           encoder = so_jsonKey f .= body
highjson                       >     |                                     ^^^^^^^^^^^^
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:128:28: error:
highjson                       >     • Couldn't match type ‘T.Text’ with ‘Key’
highjson                       >       Expected: Pair
highjson                       >         Actual: (T.Text, Value)
highjson                       >     • In the expression: pair
highjson                       >       In the expression: [pair]
highjson                       >       In the expression: ([pair], encoder)
highjson                       >     |
highjson                       > 128 |                       in ([pair], encoder)
highjson                       >     |                            ^^^^
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:143:31: error:
highjson                       >     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
highjson                       >     • In the first argument of ‘(.=)’, namely ‘rf_jsonKey f’
highjson                       >       In the expression: rf_jsonKey f .= rf_get f val
highjson                       >       In an equation for ‘encoder’:
highjson                       >           encoder = rf_jsonKey f .= rf_get f val
highjson                       >     |
highjson                       > 143 |                     encoder = rf_jsonKey f .= rf_get f val
highjson                       >     |                               ^^^^^^^^^^^^
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:144:29: error:
highjson                       >     • Couldn't match type ‘T.Text’ with ‘Key’
highjson                       >       Expected: [Pair]
highjson                       >         Actual: [(T.Text, Value)]
highjson                       >     • In the expression: pair : ps
highjson                       >       In the second argument of ‘loop’, namely
highjson                       >         ‘(pair : ps, encoder <> encoding)’
highjson                       >       In the expression: loop fs (pair : ps, encoder <> encoding)
highjson                       >     |
highjson                       > 144 |                 in loop fs (pair : ps, encoder <> encoding)
highjson                       >     |                             ^^^^^^^^^
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:144:36: error:
highjson                       >     • Couldn't match type ‘Key’ with ‘T.Text’
highjson                       >       Expected: [(T.Text, Value)]
highjson                       >         Actual: [Pair]
highjson                       >     • In the second argument of ‘(:)’, namely ‘ps’
highjson                       >       In the expression: pair : ps
highjson                       >       In the second argument of ‘loop’, namely
highjson                       >         ‘(pair : ps, encoder <> encoding)’
highjson                       >     |
highjson                       > 144 |                 in loop fs (pair : ps, encoder <> encoding)
highjson                       >     |                                    ^^
highjson                       > 
highjson                       > /tmp/stack-251a96d31c6a6da7/highjson-0.5.0.0/src/Data/HighJson/Types.hs:183:54: error:
highjson                       >     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
highjson                       >     • In the second argument of ‘(.:)’, namely ‘so_jsonKey o’
highjson                       >       In the second argument of ‘($)’, namely ‘obj .: so_jsonKey o’
highjson                       >       In the expression: fmap (so_prism o #) $ obj .: so_jsonKey o
highjson                       >     |
highjson                       > 183 |                         fmap (so_prism o #) $ obj .: so_jsonKey o
highjson                       >     |                                                      ^^^^^^^^^^^^
```
